### PR TITLE
Work around glibc's fesetenv bugs

### LINKED ISSUE #187: Differences in CPU behavior cause failing x86 tests on Travis CI
Many of the Remill instruction tests fail on Travis, and not even deterministically. They do not fail locally on developer machines, so we have been ignoring the issue and letting it annoy us for a while now.

Sometimes all of the tests pass. Re-running the build job myself tonight I have seen 100% pass, one instruction test fail, or 3 fail, or so many fail that it stopped running tests.

### Usually failing
`FTST`

### Occasionally failing
 `TZCNT` and `LZCNT`

### Seen failing at least once
The floating-point conditional move instructions (all of these tests failed): `FCMOVNU`, `FCMOVNB`, `FCMOVNE`, `FCMOVBE`, `FCMOVNBE`, `FCMOVU`, etc.

## Tips for Troubleshooting on Travis CI
We have enabled "debug builds" on our Travis CI repo. By using the API, you can trigger a debug build session. Use your own authorization token in place of the `**********`. Use your own Job ID in place of the `314970938`.

```shell
curl -s -X POST \ 
  -H "Content-Type: application/json" \ 
  -H "Accept: application/json" \ 
  -H "Travis-API-Version: 3" \ 
  -H "Authorization: token *************" \
   -d "{\"quiet\": true}" \   https://api.travis-ci.org/job/314970938/debug
```

Then wait multiple minutes for a response from the API (sometimes it does not respond, just do it again). Check the status on https://travis-ci.org/trailofbits/remill/builds/ as well, it will eventually trigger and say "pending". Using the web UI, observe the build log for the line with SSH instructions.

SSH in, and run the following commands to perform the Travis build steps and debug the tests:
```shell
travis_run_before_install
travis_run_install
travis_run_before_script
travis_run_script
sudo apt-get install gdb
gdb ./tests/X86/run-amd64_avx-tests
```

As usual, you definitely want to comment out some of the tests rather than build them all.

Once in GDB, you can run steps similar to this:
```gdb
handle SIGFPE nostop noprint
set $native = (State *)&gNativeState
set $lifted = (State *)&gLiftedState
b /home/travis/build/trailofbits/remill/tests/X86/Run.cpp:564
run
p/x $native->rflag
p/x $lifted->rflag
```

To scroll up/down in the terminal session you have to use the awful `ctrl-b [` and then use the arrow keys until you want to stop with `q`. Suggest you just view the log in the Travis CI web UI.

***Note*** you will get booted after ~49 minutes.

### PR DESCRIPTION
**Pull request by artemdinaburg**
Set the mxcsr manually to clear exceptions and ignore denormals.
Some older glibc versions do not do this, and it causes havok in our lifted code.

Another fix for now closed #187 since that issue re-appeared.

### CODE REVIEW

File: tests/X86/Run.cpp [hunk 1]
```diff
@@ -487,6 +487,21 @@ static void ResetFlags(void) {
...
+// clear the exception flags in mxcsr
+// *and* set MXCSR to ignore denormal exceptions
+// this is done by newer (after 2015) glibcs
+// but is missing in older versions
+// see: https://sourceware.org/ml/libc-alpha/2015-10/msg01020.html
+static void FixGlibcMxcsrBug() {
+  const uint32_t FE_ALL_EXCEPT_X86 = (FE_ALL_EXCEPT | __FE_DENORM);
+  uint32_t mxcsr = 0; // temporary holds our mxcsr
+  asm("stmxcsr %0;" : "=m"(mxcsr));
+  // assumes the rest of MXCSR was santely set by fesetenv
```
Comment (mike-myers-tob) [inline tests/X86/Run.cpp]: "sanely"

File: tests/X86/Run.cpp [hunk 2]
```diff
@@ -487,6 +487,21 @@ static void ResetFlags(void) {
...
 }
 
+// clear the exception flags in mxcsr
+// *and* set MXCSR to ignore denormal exceptions
+// this is done by newer (after 2015) glibcs
+// but is missing in older versions
+// see: https://sourceware.org/ml/libc-alpha/2015-10/msg01020.html
+static void FixGlibcMxcsrBug() {
+  const uint32_t FE_ALL_EXCEPT_X86 = (FE_ALL_EXCEPT | __FE_DENORM);
+  uint32_t mxcsr = 0; // temporary holds our mxcsr
```
Comment (mike-myers-tob) [inline tests/X86/Run.cpp]: "temporarily"

File: tests/X86/Run.cpp [hunk 3]
```diff
@@ -487,6 +487,21 @@ static void ResetFlags(void) {
   asm("push %0; popfq;" : : "m"(gRflagsInitial));
 }
 
+// clear the exception flags in mxcsr
+// *and* set MXCSR to ignore denormal exceptions
+// this is done by newer (after 2015) glibcs
```
Comment (mike-myers-tob) [inline tests/X86/Run.cpp]: Maybe worth specifically mentioning the routine with the error: "// this is done properly by std::fsetenv in glibc after ~2015, but was broken in earlier versions."
